### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by StanIsAdmin** [StanIsAdmin/PyProt#1]
P1
- [x] Compare results with LALIGN
- [x] Local alignment : begin from ALL maximums
- [x] Local sub optimal alignment : how many rounds (use minimum size limit ?) / where to look for maximums (everywhere ?) ? Keep previous paths at zero on subsequent rounds ?
- [x] Tell which format I'm parsing, support more ?
- [x] Document using course slides
